config/routes.rb
Rails.application.routes.draw do
  resources :enderecos

  resources :menu
  resources :pacientes do
      end
  resources :consulta
  resources :medicos

    


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/paciente.rb
class Paciente < ApplicationRecord
    has_many :consultum, dependent: :destroy
    has_many :medicos, through: :consultum
    has_one :endereco, :dependent => :destroy
    accepts_nested_attributes_for :endereco, allow_destroy: true
    validates :nome, length: { minimum: 4 } ,presence: true
    validates :cpf, length: { is: 11 } ,presence: true, numericality: { only_integer: true }, uniqueness: true
    validates :email, length: { minimum: 11 }, presence: true, uniqueness: true
    validates :data_de_nascimento, presence: true
    validate :validarData

  def validarData
    if data_de_nascimento.present? && data_de_nascimento > Date.today
      errors.add(:dataNascimento, "Data invalida")
    end
  end
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
  before_action :set_paciente, only: %i[ show edit update destroy ]

  # GET /pacientes or /pacientes.json
  def index
    @pacientes = Paciente.all
  end

  # GET /pacientes/1 or /pacientes/1.json
  def show
  end

  # GET /pacientes/new
  def new
    @paciente = Paciente.new
    @paciente.build_endereco
  end

  # GET /pacientes/1/edit
  def edit
  end

  # POST /pacientes or /pacientes.json
  def create
    @paciente = Paciente.new(paciente_params)
    @paciente.endereco = Endereco.new(paciente_params[:endereco_attributes])

    respond_to do |format|
      if @paciente.save
        format.html { redirect_to paciente_url(@paciente), notice: "Paciente was successfully created." }
        format.json { render :show, status: :created, location: @paciente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pacientes/1 or /pacientes/1.json
  def update
    respond_to do |format|
      if @paciente.update(paciente_params)
        format.html { redirect_to paciente_url(@paciente), notice: "Paciente was successfully updated." }
        format.json { render :show, status: :ok, location: @paciente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @paciente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pacientes/1 or /pacientes/1.json
  def destroy
    @paciente.destroy

    respond_to do |format|
      format.html { redirect_to pacientes_url, notice: "Paciente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paciente
      @paciente = Paciente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def paciente_params
      params.require(:paciente).permit(:nome, :cpf, :email, :data_de_nascimento,endereco_attributes:
        [:cep, :logradouro, :cidade, :bairro, :complemento])
    end
end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/_form.html.erb
<%= form_with(model: paciente) do |form| %>
  <% if paciente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(paciente.errors.count, "error") %> prohibited this paciente from being saved:</h2>

      <ul>
        <% paciente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :data_de_nascimento, style: "display: block" %>
    <%= form.date_field :data_de_nascimento %>
  </div>
  <div>
    <h2>Endereço</h2>
    <%= form.fields_for :endereco do |endereco_form| %>
      <p>
        <%= endereco_form.label :cep %><br>
        <%= endereco_form.text_field :cep %>
      </p>

      <p>
        <%= endereco_form.label :cidade %><br>
        <%= endereco_form.text_field :cidade %>
      </p>

      <p>
        <%=endereco_form.label :bairro %><br>
        <%= endereco_form.text_field :bairro %>
      </p>

      <p>
        <%= endereco_form.label :logradouro %><br>
        <%= endereco_form.text_field :logradouro %>
      </p>

      <p>
        <%= endereco_form.label :complemento %><br>
        <%= endereco_form.text_field :complemento %>
      </p>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pacientes/_paciente.html.erb
<div id="<%= dom_id paciente %>">
  <h2>Dados Pessoais</h2>
  <ul>
  <p>
    <strong>Nome:</strong>
    <%= paciente.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= paciente.cpf %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= paciente.email %>
  </p>

  <p>
    <strong>Data de nascimento:</strong>
    <%= paciente.data_de_nascimento %>
  </p>
  </ul>
<h2>Endereço</h2>
  <ul>
  <p>
    <strong>Cep:</strong>
    <%= paciente.endereco.cep %>
  </p>

  <p>
    <strong>Cidade:</strong>
    <%= paciente.endereco.cidade %>
  </p>

  <p>
    <strong>Bairro:</strong>
    <%= paciente.endereco.bairro %>
  </p>

  <p>
    <strong>Logradouro:</strong>
    <%= paciente.endereco.logradouro %>
  </p>

  <p>
    <strong>Complemento:</strong>
    <%= paciente.endereco.complemento %><br>
  </p>
  </ul>
  </div>

app/views/pacientes/edit.html.erb
<h1>Editing paciente</h1>

<%= render "form", paciente: @paciente %>

<br>

<div>
  <%= link_to "Show this paciente", @paciente %> |
  <%= link_to "Back to pacientes", pacientes_path %>
</div>

app/views/pacientes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pacientes</h1>

<div id="pacientes">
  <% @pacientes.each do |paciente| %>
    <%= render paciente %>


    <p>
      <%= link_to "Show this paciente", paciente %><br>
      ----------------------------------------------------
    </p>
  <% end %>
</div>

<%= link_to "New paciente", new_paciente_path %><br>
<br>
<%= link_to "back menu", menu_index_path %>

app/views/pacientes/new.html.erb
<h1>New paciente</h1>

<%= render "form", paciente: @paciente %>

<br>

<div>
  <%= link_to "Back to pacientes", pacientes_path %>
</div>

app/views/pacientes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @paciente %>

<div>
  <%= link_to "Edit this paciente", edit_paciente_path(@paciente) %> |
  <%= link_to "Back to pacientes", pacientes_path %>

  <%= button_to "Destroy this paciente", @paciente, method: :delete %>
</div>