config/routes.rb
Rails.application.routes.draw do
  resources :enderecos

  resources :menu
  resources :pacientes do
      end
  resources :consulta
  resources :medicos

    


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/medico.rb
class Medico < ApplicationRecord
    has_many :consultum, dependent: :destroy
    has_many :pacientes, through: :consultum
    validates :nome, length: { minimum: 4 }, presence: true
    validates :cpf, length: { is: 11 }, presence: true, numericality: { only_integer: true }, uniqueness: true
    validates :email, length: { minimum: 11 }, presence: true, uniqueness: true
    validates :especialidade, presence: true, length: { in: 4..20 }
    validates :crm, numericality: { only_integer: true }, presence: true, uniqueness: true
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
  before_action :set_medico, only: %i[ show edit update destroy ]

  # GET /medicos or /medicos.json
  def index
    @medicos = Medico.all
  end

  # GET /medicos/1 or /medicos/1.json
  def show
  end

  # GET /medicos/new
  def new
    @medico = Medico.new
  end

  # GET /medicos/1/edit
  def edit
  end

  # POST /medicos or /medicos.json
  def create
    @medico = Medico.new(medico_params)

    respond_to do |format|
      if @medico.save
        format.html { redirect_to medico_url(@medico), notice: "medico was successfully created." }
        format.json { render :show, status: :created, location: @medico }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicos/1 or /medicos/1.json
  def update
    respond_to do |format|
      if @medico.update(medico_params)
        format.html { redirect_to medico_url(@medico), notice: "Medico was successfully updated." }
        format.json { render :show, status: :ok, location: @medico }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @medico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicos/1 or /medicos/1.json
  def destroy
    @medico.destroy

    respond_to do |format|
      format.html { redirect_to medicos_url, notice: "Medico was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medico
      @medico = Medico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def medico_params
      params.require(:medico).permit(:nome, :cpf, :email, :especialidade, :crm)
    end
end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/views/medicos/_form.html.erb
<%= form_with(model: medico) do |form| %>
  <% if medico.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(medico.errors.count, "error") %> prohibited this medico from being saved:</h2>

      <ul>
        <% medico.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :especialidade, style: "display: block" %>
    <%= form.text_field :especialidade %>
  </div>

  <div>
    <%= form.label :crm, style: "display: block" %>
    <%= form.text_field :crm %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/medicos/_medico.html.erb
<div id="<%= dom_id medico %>">
  <p>
    <strong>Nome:</strong>
    <%= medico.nome %>
  </p>

  <p>
    <strong>Cpf:</strong>
    <%= medico.cpf %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= medico.email %>
  </p>

  <p>
    <strong>Especialidade:</strong>
    <%= medico.especialidade %>
  </p>

  <p>
    <strong>Crm:</strong>
    <%= medico.crm %>
  </p>

  <p>
    <strong>Consultas:</strong>
  <div id="consultum">
    <% medico.consultum.each do |consulta| %>
      <style>
        table{
            width: 500px;
            border-collapse: collapse;

        }
        td {
            border: 1px solid black;
            padding: 8px;

        }
      </style>
      <ul>
        <table>
          <tr>
            <td> Consulta </td>
            <td> Paciente </td>
            <td> Data e Hora </td>
          </tr>
          <tr>
            <td><%= consulta.id %></td>
            <td><%= consulta.paciente.nome %></td>
            <td><%= consulta.data_hora %></td>
          </tr>
        </table>
      </ul>
    <% end %>
  </div>
  </p>

</div>

app/views/medicos/edit.html.erb
<h1>Editing medico</h1>

<%= render "form", medico: @medico %>

<br>

<div>
  <%= link_to "Show this medico", @medico %> |
  <%= link_to "Back to medicos", medicos_path %>
</div>

app/views/medicos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Medicos</h1>

<div id="medicos">
  <% @medicos.each do |medico| %>
    <%= render medico %>
    <p>
      <%= link_to "Show this medico", medico %><br>
      ---------------------------------------------
    </p>
  <% end %>
</div>

<%= link_to "New medico", new_medico_path %><br>
<%= link_to "Back to menu", menu_index_path %>

app/views/medicos/new.html.erb
<h1>New medico</h1>

<%= render "form", medico: @medico %>

<br>

<div>
  <%= link_to "Back to medicos", medicos_path %>
</div>

app/views/medicos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @medico %>



<div>
  <%= link_to "Edit this medico", edit_medico_path(@medico) %> |
  <%= link_to "Back to medicos", medicos_path %>

  <%= button_to "Destroy this medico", @medico, method: :delete %>
  <%= link_to "Back to menu", menu_index_path %>
</div>